### ISSUE TITLE
Class private methods are not enabled

### ISSUE THREAD

**Issue by pehe** [VadimDez/ng2-pdf-viewer#956] opened 2022-12-08 15:35 UTC
Hi Vadim,

I have recently upgraded to Angular 15 and I am getting the following error when compiling the application. Could you please check if this is an issue or my fault.

Thanks,
Petr

./node_modules/pdfjs-dist/build/pdf.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
SyntaxError: ...\ClientApp\node_modules\pdfjs-dist\build\pdf.js: Class private methods are not enabled. Please add `@babel/plugin-proposal-private-methods` to your configuration.     
  3253 |   #objs = Object.create(null);
  3254 |
> 3255 |   #ensureObj(objId) {
       |   ^
  3256 |     const obj = this.#objs[objId];
  3257 |
  3258 |     if (obj) {

./node_modules/pdfjs-dist/web/pdf_viewer.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
SyntaxError: C...\ClientApp\node_modules\pdfjs-dist\web\pdf_viewer.js: Class private methods are not enabled. Please add `@babel/plugin-proposal-private-methods` to your configuration.
  498 |   }
  499 |
> 500 |   #goToDestinationHelper(rawDest, namedDest = null, explicitDest) {
      |   ^
  501 |     const destRef = explicitDest[0];
  502 |     let pageNumber;

**Comment by VadimDez** [comment] 2022-12-08 15:37
Duplicate of #955

**Closed by VadimDez** 2022-12-08 15:37 UTC
