### ISSUE TITLE
ng2-pdf-viewer on incorrect source issue

### ISSUE THREAD

**Issue by Wenqiang01** [VadimDez/ng2-pdf-viewer#227] opened 2017-12-18 09:10 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- <pdf-viewer [src]="pdfSrc" ></pdf-viewer>
- [ ] if the pdfSrc is invalid or cannot be found, do we have method to handle these kind issue
- [ ] if the pdfSrc return 404, how should I handle this kind issue, thank you
```

**Comment by aadeez** [comment] 2017-12-19 13:14
Kindly add fonts from **shree lipi(ttf), kruti dev(ttf), walkman chanakya(ttf)** , if required i will send you the fonts.

**Comment by Wenqiang01** [comment] 2017-12-21 01:46
Hi @aadeez  
What do you mean by adding fonts,   my question is when the src attribute is not a PDF path or a invalid path, how can we handle this kind issue.

**Comment by VadimDez** [comment] 2017-12-21 08:52
Similar to #166

**Comment by VadimDez** [comment] 2017-12-30 18:16
Closing as duplicate of #166

**Closed by VadimDez** 2017-12-30 18:16 UTC
