### ISSUE TITLE
Zoom in document

### ISSUE THREAD

**Issue by quentinmachard-niji** [VadimDez/ng2-pdf-viewer#263] opened 2018-01-29 11:09 UTC
Hello,

Your plugin is very great, but I have a problem with it in my project. I can't pinch to zoom in document when display it... I test it on Android and iOS 11.

Here is my call :
```
<pdf-viewer *ngIf="!error"
                [src]="{
                  url: url,
                  httpHeaders: httpHeaders
                }"
                [original-size]="false"
                [render-text]="true"
                style="display: block;"
                (after-load-complete)="onLoaded($event)"
                (error)="onError($event)"></pdf-viewer>
```

Thank you very much !

**Comment by VadimDez** [comment] 2018-02-04 11:25
Possibly duplicate of #22

**Comment by mill1** [comment] 2018-05-31 11:47
Zoom does not seem to work in combination with [original-size]="false". Set [original-size]="true" and try again.

**Comment by zmeeagain** [comment] 2019-10-16 12:03
Worked with `[original-size]="false"` when a `display: block;` class was applied to the `pdf-viewer` element.

**Closed** 2019-10-19 20:31 UTC
