### ISSUE TITLE
Loader is stuck when upgrade to newest version

### ISSUE THREAD

**Issue by gabayarden** [VadimDez/ng2-pdf-viewer#863] opened 2022-02-06 12:40 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

I used version 6.4.0 until now with angular 13.1.0 and everything worked fine.
I now upgraded ng2-pdf-viewer into newest version (7.0.2) and I'm facing an issue that the loader is not stopping to spin.
I tried to use the demo pdf from npmjs but is is happed there as well.
I don't see any error on console, and the "after-load-complete" event is indeed fired but still it looks like it is loading.

SS:
![image](https://user-images.githubusercontent.com/3463053/152681098-ce9b7114-e409-4e7c-bc25-d38a2ec57b60.png)
![image](https://user-images.githubusercontent.com/3463053/152681120-198244c9-173a-4c09-b398-2f3ee6e550d8.png)

**Comment by anddam** [comment] 2022-02-16 23:26
Possible duplicate of #846.

**Comment by VadimDez** [comment] 2022-02-19 21:28
@gabayarden could you test if new version 8.0.0 fixes your issue?

**Comment by anddam** [comment] 2022-02-20 13:53
I did a test setting up  a new project with node 16, angular ~13 and new ng2-pdf-viewer 8.0.0 and I can confirm it works now.

If you have a chance bump the homepage stackblitz's package.json.

**Comment by VadimDez** [comment] 2022-02-20 13:55
Fixed by version 8.0.0

**Closed by VadimDez** 2022-02-20 13:55 UTC

**Comment by onedotover** [comment] 2022-02-21 23:10
I was having this issue in Angular 12 and 13 with version 7 and 8. Setting style="width: ##px, height: ##px" on the pdf-viewer component fixed the issue for me. Is it required to have the width and height set?

**Comment by VadimDez** [comment] 2022-02-22 08:19
Yes, since version 7.0.0, container should have width and height set, see https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/7.0.0
