### ISSUE TITLE
Cannot find name 'PDFDocumentProxy' when upgrading from v2.x to v3.x

### ISSUE THREAD

**Issue by kreuzersteve** [VadimDez/ng2-pdf-viewer#208] opened 2017-11-13 11:57 UTC
Was trying to upgrade to the newest version 3.0.1 (coming from 2.0.3). Strictly followed the setup as decribed in the "Usage"-section but it's giving me the error:
Cannot find name 'PDFDocumentProxy'
Probably an error related to the after-load-complete-Attribute.
I removed the type from the callback-function in order to get it working again, but I'm not entirely sure if just removing it will give me other drawbacks.

**Comment by VadimDez** [comment] 2017-11-13 13:41
Duplicate of #200

**Closed by VadimDez** 2017-11-13 13:41 UTC
