### ISSUE TITLE
UnknownErrorException: The API version "1.9.640" does not match the Worker version "1.10.81"

### ISSUE THREAD

**Issue by aadeez** [VadimDez/ng2-pdf-viewer#188] opened 2017-10-24 07:17 UTC
UnknownErrorException {name: "UnknownErrorException", message: "The API version "1.9.640" does not match the Worker version "1.10.81".", details: "Error: The API version "1.9.640" does not match the Worker version "1.10.81".", __zone_symbol__currentTask: ZoneTask}

i have tried reinstalling but it didn't work.

**Comment by VadimDez** [comment] 2017-10-24 08:15
Duplicate of #179

**Comment by VadimDez** [comment] 2017-10-27 17:30
Let me know if #179 does fix your problem

**Closed** 2017-11-06 19:05 UTC
