### ISSUE TITLE
passing custom headers & angular4.3 http auth interceptors & Bearer token

### ISSUE THREAD

**Issue by robert-king** [VadimDez/ng2-pdf-viewer#211] opened 2017-11-15 05:20 UTC
Hi there, it wasn't obvious from the documentation how to add custom headers. I ended up using a PDFSource. Also, it would be nice if it could use my HttpInterceptor which adds auth and other headers and checks and retries & token refreshes.

Here's the code I had to come up with to get it working with bearer token:

  ```
<pdf-viewer [src]="pdfSource"
              [render-text]="true"
              style="display: block;"
  ></pdf-viewer>


import {Component, Input, OnInit} from '@angular/core';
import {environment} from "../../environments/environment";
import {AuthService} from "../auth.service";

@Component({
  selector: 'app-pdf-viewer',
  templateUrl: './pdf-viewer.component.html',
  styleUrls: ['./pdf-viewer.component.scss']
})
export class PdfViewerComponent implements OnInit {
  @Input() id: string
  @Input() type: string
  pdfLink: string
  pdfSource: any

  constructor(private authService: AuthService) {
  }

  ngOnInit() {
    if (this.type == 'pdf') {
      this.pdfLink = `${environment.celoApiEndpoint}/api/Consents/${this.id}`
    } else if (this.type == 'document') {
      this.pdfLink = `${environment.celoApiEndpoint}/api/PatientFiles/${this.id}`
    }

    this.pdfSource = {
      url: this.pdfLink,
      // data?: Uint8Array;
      httpHeaders: {'Authorization': this.authService.getAuth(), 'CeloAuthorization': environment.celoAuth}
      // password?: string;
    }

  }

}

```

edit: finished solution if anyone needs it, get arraybuffer, convert to uint8array:

```
export class PdfViewerComponent implements OnInit {
  @Input() id: string
  @Input() type: string
  pdfLink: string
  pdfSource: any
  isLoading = false

  constructor(private http: HttpClient) {
  }

  ngOnInit() {
    if (this.type == 'pdf') {
      this.pdfLink = `${environment.celoApiEndpoint}/api/Consents/${this.id}`
    } else if (this.type == 'document') {
      this.pdfLink = `${environment.celoApiEndpoint}/api/PatientFiles/${this.id}`
    }
    this.loadPdf()
  }

  private loadPdf() {
    this.isLoading = true
    this.http.get<ArrayBuffer>(this.pdfLink, {responseType: 'arraybuffer' as 'json'})
      .do(()=>this.isLoading=false)
      .subscribe((ab) => {
        this.pdfSource = {
          data: new Uint8Array(ab)
        }
      })
  }

}

```

**Comment by robert-king** [comment] 2017-11-15 05:25
I guess I could use httpClient.get, and convert the blob to a Uint8Array, and use an *ngIf="fileLoaded"

**Comment by VadimDez** [comment] 2018-05-30 20:18
Duplicate of #309

**Closed by VadimDez** 2018-05-30 20:18 UTC

**Comment by experimint** [comment] 2019-10-16 10:42
Thanks a bunch @robert-king
