### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by TimMeissner** [VadimDez/ng2-pdf-viewer#322] opened 2018-05-04 08:52 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

When updating to angular 6 (and angular-cli 6.0) i get the following errors when starting up the application with `ng serve`:

WARNING in ./node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'zlib' in '/Users/timmeissner/coyo/coyo-frontend/ngx/node_modules/pdfjs-dist/build'

ERROR in ../node_modules/reserved-words/lib/reserved-words.js
Module not found: Error: Can't resolve 'assert' in '/Users/timmeissner/coyo/coyo-frontend/node_modules/reserved-words/lib'
ℹ ｢wdm｣: Failed to compile.

**Comment by fengerzh** [comment] 2018-05-06 00:25
You have to work harder man, we just released Angular 5 version days ago, now it comes Angular 6. 😜

**Comment by rsheptolut** [comment] 2018-05-08 09:19
I'm just some guy off the internet, but.

The first one `Can't resolve 'zlib'` is just a warning in pdf.js (not related to the author of ng2-pdf-viewer I think). If you actually use the library it works properly. It's probably just a new warning that was hidden before, the compiler somehow peeks in `require()` statements in a way that it hasn't before. This `require()` statement in pdf.js won't be executed unless you do some really obscure stuff with SVGs as briefly mentioned [here](https://github.com/mozilla/pdf.js/issues/8774#issuecomment-322294145).

The second one `Can't resolve 'assert' in '/node_modules/reserved-words/lib` is straight up irrelevant here (just some other library).

That said, `ng2-pdf-viewer` in its current version still works for me even after upgrading to Angular 6.

**Comment by shariqshahzad** [comment] 2018-05-11 10:15
did you guys manage any solution for this warning ?

**Comment by rsheptolut** [comment] 2018-05-11 16:51
@shariqshahzad Mostly anger management for now. Trying to cope with it. The way to remove the warning is to first find out which part of the whoole Angular 6 update introduced it, and file an issue in the Angular repo, or maybe in a webpack repo, or maybe these guys will tell you that pdf.js guys must now somehow code this differently... I don't have enough know-how to get to the bottom of this to at least file the issue to the right place.

**Comment by warapitiya** [comment] 2018-05-13 03:31
Greetings!! ok to start this is something to do with Webpack as I believe, since Webpack 4 is written from the ground up, now it parse the whole file before it extracts required code.

Since [PDFjs code](https://github.com/mozilla/pdfjs-dist/blob/master/build/pdf.js#L15177) needed [zlib](https://nodejs.org/api/zlib.html) only if we run it on server side. But the problem is PDFjs includes the browser needed logic and server needed logic in the same js file.

I would say to start we can file a request to modulerized the PDFjs logic to seperate files so that any library that uses it can import correct required file.

```txt
pdfjs.browser.js
pdfjs.browser.min.js
pdfjs.server.js
pdfjs.server.min.js
```

**Comment by shariqshahzad** [comment] 2018-05-13 11:25
i have managed to get rid of this warning but the solution is not a proper one if someone needs to know i can share

**Comment by Shay12tg** [comment] 2018-05-14 02:40
@shariqshahzad  please do :) this warning is annoying!

**Comment by shariqshahzad** [comment] 2018-05-14 12:33
I'm sorry that is not working :'(

**Comment by fengerzh** [comment] 2018-05-16 01:55
@ColinT I tried add `zlib` folder in `node_modules` and add `package.json` as you mentioned, but when run `npm run start`, it still show:

```
WARNING in ./node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'zlib' in '/Users/zhangjing/Projects/qiban/oa-web/node_modules/pdfjs-dist/build'
ℹ ｢wdm｣: Compiled with warnings.
```

**Comment by Shay12tg** [comment] 2018-05-16 02:00
Thanks @ColinT 
Got it working by installing stream-browserify and browserify-zlib and adding
    "paths": {
      "stream": ["../node_modules/stream-browserify/index.js"],
      "zlib": ["../node_modules/browserify-zlib/lib/index.js"]
    }
to the compilerOptions on tsconfig.json

**Comment by fengerzh** [comment] 2018-05-16 06:51
@ColinT Thank you, after adding an empty `index.js`, I finally get rid of the ugly `zlib` warning.

**Comment by lordgreg** [comment] 2018-05-25 13:11
Waiting for the proper issue. Creating blind node module is nothing else but a hack. This is something it has to be updated in the module itself. Its a stricter warning and can be fixed. 👍

**Comment by enyachoke** [comment] 2018-06-04 11:37
I used this in the package.json
```Json
"browser": {
    "fs": false,
    "path": false,
    "os": false,
    "stream": false,
    "zlib": false
  }
```
To ignore the libs

**Comment by selvavmokshagroup** [comment] 2018-06-12 05:44
@enyachoke Thank you, its works now

**Comment by Ristaaf** [comment] 2018-06-12 12:22
@enyachoke Which package.json is that? 

I tried adding it to my package.json but still get the zlib warning! 

Does it need to be in node_modules/ng2-pdf-viewer/package.json or in node_modules/pdfjsdist/package.json? In those cases it is no go for me, as I cannot touch any files in node_modules, that folder is not checked in to version handling, I would in that case have to automatically write to the files in a post-install script and that gets hairy really fast!

**Comment by lordgreg** [comment] 2018-06-12 12:29
Had exactly the same issue. If this should update the package.json from the module itself its not a proper update.

**Comment by enyachoke** [comment] 2018-06-13 05:32
@Ristaaf  am using angular cli so I add that my angular cli project.

**Comment by Ristaaf** [comment] 2018-06-13 05:43
@enyachoke Ok, I also use angular cli, but I still get the zlib warning when even when adding the browser field to my package.json, I read up on it a bit and it should definitely work as you describe, so I will have to check what the problem for me is...

**Comment by maxmumford** [comment] 2018-06-13 08:05
@enyachoke can you paste your entire package.json here so we can try with the same dependency versions etc?

**Comment by j-nord** [comment] 2018-06-13 10:23
@enyachoke 
We have the same problem: Module not found: Error: Can't resolve 'zlib' 
The browser entry does not work in the package.json. We use also angular-cli.

**Comment by j-nord** [comment] 2018-06-19 14:56
@VadimDez
Is very nice when you write new tools. **But it would be better if this existing tool is also maintained.** Can we hope for a solution for this problem?

**Comment by fengerzh** [comment] 2018-06-19 15:49
As this project is an open source project, that means everyone can fork a copy of the code and fix the issue before raising a PR.

**Comment by chiragsenjaliya** [comment] 2018-06-20 09:55
@j-nord  @Ristaaf  did you reinstall package after that? And also please stop ng serve!

**Comment by sharppc** [comment] 2018-06-20 20:11
@chiragsenjaliya I added the browser entry to the package.json, made sure no instances of Node.exe were running, deleted package-lock.json, uninstalled and reinstalled ng2-pdf-viewer, and I still get the warning.

More details would be beneficial.

**Comment by Ristaaf** [comment] 2018-06-25 13:44
@chiragsenjaliya I did this:
with nothing running (I don't even use ng serve, only ng build)

Using gitbash on Windows 10
1. Added the browser part to package.json
2. npm cache clean --force
3. rm -rf node_modules
4. rm -f package-lock.json
5. npm install
6. ng build

And I get the zlib warning

**Comment by chiragsenjaliya** [comment] 2018-06-25 15:05
@Ristaaf @sharppc add this in your package.json:
"browser": {
    "zlib": false
  }
I hope it might help.
Thanks 😊

**Comment by oguimbal** [comment] 2018-06-26 16:11
If it helps: you can easily propagate @ColinT solution to other devs in your team using a postinstall script:

in your **package.json**

```
{
  "scripts": {
    "postinstall": "node ./postinstall.js"
  }
}
```

Then write a **postinstall.js** file in your project root

```
//  Fake zlib  (see https://github.com/VadimDez/ng2-pdf-viewer/issues/322)
const fs = require('fs');
var zl = './node_modules/zlib';
if(!fs.existsSync(zl))
  fs.mkdirSync(zl);
fs.writeFileSync(zl+'/package.json', `{
  "name": "zlib",
  "version": "1.0.0"
}`);
fs.writeFileSync(zl+'/index.js', '');
```


"Works" like a charm. No more zlib.

**Comment by quirogamauricio** [comment] 2018-07-19 14:14
@enyachoke thank you, your proposed solution worked like a charm for me.
I only added :
`"browser": {
    "zlib": false
  }` to my Angular project's `package.json`, stopped the running application and started it again with `ng serve`. I also tried building it with `ng build` and i didn't get that warning anymore.
I'm using npm v `6.2.0` and Node v`8.11.3` if that helps.

**Comment by chiragsenjaliya** [comment] 2018-07-19 16:20
I am really glad it helps! Cheers!

**Comment by treveshan** [comment] 2018-07-21 17:13
Added 
"browser": {
    "zlib": false
  }
to the ng package.json worked for me . NB: I'm using NG 6

**Comment by harinikprabhu** [comment] 2018-07-31 20:15
Some IDEs like Visual Studio deletes a fake package (like the proposed zlib hack here) and throws the same error again. It is better to do it in other ways mentioned here.

**Comment by andrewjsaid** [comment] 2018-08-06 13:16
@Ristaaf @sharppc I had the same problem, then removed `"baseUrl": "./"`, from `src/tsconfig.app.json` and the error disappeared for me. That setting seems to come with the ASP.NET Core angular template - have no idea what it does though.

**Comment by TheZoker** [comment] 2018-08-06 16:52
The `"browser": { "zlib": false }` does not solve anything for me :/
Only way is to mock the `zlib` folder

Any advise?

**Comment by Mysame** [comment] 2018-08-09 09:44
Will be fixed on Mozilla's side of things in pdf.js version 2:
https://github.com/mozilla/pdf.js/pull/9924

**Comment by thatgirlcancode** [comment] 2018-08-14 14:56
Looks like this was fixed a few weeks ago... https://github.com/mozilla/pdf.js/pull/9924/files

**Comment by Ristaaf** [comment] 2018-08-17 11:55
@andrewjsaid Interesting, however we have edited baseUrl ourselves and are dependent on our new value in parts of our build system, so that is unfortunately not an option, but thanks for clearing out why the package.json browser thing did not work in my case. For now I am going with the fake zlib package created with a post-install script.

**Comment by legalbrickstechnology-dcm** [comment] 2018-09-13 09:30
This is irritating :( the browser in package.json suggestion also didnt work for me (using 7 beta5 currently) 
However the post script workaround removes the warning

**Comment by joaoyuki** [comment] 2018-09-16 15:32
> @Ristaaf @sharppc add this in your root folder package.json:
> {
> "name": "drive",
> "version": "0.0.0",
> "scripts": {
> "ng": "ng",
> "start": "ng serve",
> "build": "ng build",
> "test": "ng test",
> "lint": "ng lint",
> "e2e": "ng e2e"
> },
> "browser": {
> "zlib": false
> },
> .....
> }
> I hope it might help.
> Thanks 😊

Thanks man! It worked for me.

**Comment by kyg9823** [comment] 2018-10-02 07:59
@joaoyuki 
When I added "browser":{"zlib":false} to package.json, I got a warning message during a build as below.

WARNING in ./node_modules/pdfjs-dist/build/pdf.js
Module not found: Error: Can't resolve 'zlib' in 'C:\Project\SNF\workspace\EHR_DEV\node_modules\pdfjs-dist\build'

Can I ignore this message?
ng2-pdf-viewer component is working well.

**Comment by LastCodeDE** [comment] 2018-10-26 07:16
Again in "ng2-pdf-viewer": "5.2.0" not yet solved.

When will it be fixed?

**Comment by dotNetAthlete** [comment] 2018-11-08 16:22
Same error in Angular 7.0.3

**Comment by dotNetAthlete** [comment] 2018-11-08 16:29
> > @Ristaaf @sharppc add this in your root folder package.json:
> > {
> > "name": "drive",
> > "version": "0.0.0",
> > "scripts": {
> > "ng": "ng",
> > "start": "ng serve",
> > "build": "ng build",
> > "test": "ng test",
> > "lint": "ng lint",
> > "e2e": "ng e2e"
> > },
> > "browser": {
> > "zlib": false
> > },
> > .....
> > }
> > I hope it might help.
> > Thanks 😊
> 
> Thanks man! It worked for me.

(I don't know why they just don't fix this)

**Closed** 2018-11-13 20:06 UTC
