### ISSUE TITLE
Pdf not showing with angular version 13.2.1 and ng2-pdf-viewer version 7.0.2

### ISSUE THREAD

**Issue by ericliu1998** [VadimDez/ng2-pdf-viewer#861] opened 2022-02-02 23:41 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [x ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I was following this [tutorial ](https://www.positronx.io/create-pdf-viewer-in-angular-with-ng2-pdf-viewer/) step by step

The pdf just doesnt show when I do an npm start.  
I am on angular version 13.2.1 and ng2-pdf-viewer version 7.0.2. 

The only way the pdf shows is when I downgrade to version 7.0.1. 
Can you please push out another update? I don't want to keep using an old version.

**Comment by michelmeeuwissen** [comment] 2022-02-16 08:09
7.0.2 also results in a none showing pdf (without error) for NG 12.2.16

**Comment by anddam** [comment] 2022-02-16 23:26
Possible duplicate of #846.

**Comment by VadimDez** [comment] 2022-02-19 09:29
Closing as duplicate of #846

**Closed by VadimDez** 2022-02-19 09:29 UTC
