### ISSUE TITLE
src as Uint8Array, shows array instead of rendering PDF

### ISSUE THREAD

**Issue by robinmaple** [VadimDez/ng2-pdf-viewer#213] opened 2017-11-22 18:18 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
in the component.ts
    pdfDownload(){
        this._http.get(this._configuration.Server+"/api/Helpers/PDFDownload?fileName='x'&folderName='x'", { responseType: ResponseContentType.ArrayBuffer })
        .map((file: Response) => file.arrayBuffer())
        .subscribe(
            (file:any) => {
                this.pdf = new Uint8Array(file);
                this.pdfTrue = true;
            }
        );
   }

in the html
    <pdf-viewer *ngIf="pdfTrue" [src]="pdf" [render-text]="true" style="display: block;">
    </pdf-viewer>

When inpect the <pdf-viewer> on the page, it's the array.

![image](https://user-images.githubusercontent.com/7815640/33143333-cf19e624-cf76-11e7-8689-32293cdaebf1.png)

Please kindly help, thanks!

**Comment by robinmaple** [comment] 2017-11-22 19:52
BTW, I'm getting a valid Uint8Array value in the pdf.

![image](https://user-images.githubusercontent.com/7815640/33147131-ebdb5d4e-cf83-11e7-8fc7-10626a022f4b.png)

**Comment by VadimDez** [comment] 2017-11-24 22:30
I've tried this and it worked for me:

```ts
this.http.get('http://localhost:8000/pdf-test.pdf', { responseType: ResponseContentType.ArrayBuffer })
      .subscribe((file: Response) => {
        this.pdfSrc = new Uint8Array(file.arrayBuffer());
      });
```

Do you get any errors?

**Comment by robinmaple** [comment] 2017-11-25 02:07
I've seen some

**Comment by VadimDez** [comment] 2017-11-25 10:02
I did reopen #88 and closing this as duplicate of #88

**Closed by VadimDez** 2017-11-25 10:02 UTC

**Comment by pradeep0024** [comment] 2022-06-24 19:21
I am still facing this issue. Couldnt show pdf (It is displaying blank) in the UI using pdfviewer using Uint8Array as a source I am able to get the Uint8Array the same way as shown above. 
pdfsource also throwing an error when provided ArrayBuffer as a source but works fine in other project with same versions.
Versions:   "ng2-pdf-viewer": "^6.3.2",.
 please let me know any solutions found.
