### ISSUE TITLE
Accessing remote PDF-files

### ISSUE THREAD

**Issue by frankmyhre** [VadimDez/ng2-pdf-viewer#83] opened 2017-04-18 19:29 UTC
Hey, 

I'm trying to use this component to open remote PDF's. I tried open one from my own page which is http, but i guess only https works. Then i tried pointing to a pdf on dropbox which has https, but then it gives me:

`Error: Uncaught (in promise): UnexpectedResponseException: Unexpected server response (0) while retrieving PDF "https://www.dropbox.com/s/dljd7yalhow2rgd/diplom_A4_s117495_trykklar.pdf?".
Error
    at g (http://localhost:8103/build/polyfills.js:3:7133)
    at UnexpectedResponseExceptionClosure (http://localhost:8103/build/main.js:115577:43)
    at Object.<anonymous> (http://localhost:8103/build/main.js:115580:2)
    at Object._typeof (http://localhost:8103/build/main.js:116279:30)
    at __w_pdfjs_require__ (http://localhost:8103/build/main.js:115149:30)
    at Object._typeof (http://localhost:8103/build/main.js:158636:23)
    at __w_pdfjs_require__ (http://localhost:8103/build/main.js:115149:30)
    at _typeof (http://localhost:8103/build/main.js:115195:18)
    at http://localhost:8103/build/main.js:115198:10
    at webpackUniversalModuleDefinition (http://localhost:8103/build/main.js:115122:20)
    at Object.<anonymous> (http://localhost:8103/build/main.js:115129:3)
    at Object.module.exports (http://localhost:8103/build/main.js:160159:30)
    at __webpack_require__ (http://localhost:8103/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8103/build/main.js:114875:1)
    at __webpack_require__ (http://localhost:8103/build/main.js:20:30)
    at g (http://localhost:8103/build/polyfills.js:3:7133)
    at l (http://localhost:8103/build/polyfills.js:3:6251)
    at l (http://localhost:8103/build/polyfills.js:3:5937)
    at http://localhost:8103/build/polyfills.js:3:6765
    at t.invokeTask (http://localhost:8103/build/polyfills.js:3:15213)
    at Object.onInvokeTask (http://localhost:8103/build/main.js:4416:37)
    at t.invokeTask (http://localhost:8103/build/polyfills.js:3:15134)
    at n.runTask (http://localhost:8103/build/polyfills.js:3:10390)
    at a (http://localhost:8103/build/polyfills.js:3:5313)
    at XMLHttpRequest.invoke (http://localhost:8103/build/polyfills.js:3:16210)`

My ionic info is:
`Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.0
Angular Core: 4.0.0
Angular Compiler CLI: 4.0.0
Node: 6.9.4
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36`

this is the http-path: http://frankmyhre.dk/Participation_in_Design_Things.pdf
and this is the dropbox-https path: https://www.dropbox.com/s/efsmw3ye689bj7b/Participation_in_Design_Things.pdf?dl=0

So is it possible to use http path? and if not why is my https path not working and what can I do to make it work?

**Comment by Newan** [comment] 2017-04-25 08:09
Your server must accept Cors:

https://enable-cors.org/server_apache.html

**Comment by VadimDez** [comment] 2017-04-27 07:55
Sounds like duplicate of #41

**Closed** 2017-05-25 11:59 UTC
