### ISSUE TITLE
Hyperlinks are not working

### ISSUE THREAD

**Issue by gaurav2887** [VadimDez/ng2-pdf-viewer#49] opened 2017-01-26 01:45 UTC
I am able to view the pdf on the browser but none of the hyperlink works. Is there any option to enable it as I am already using [render-text]="true" and that did not enable hyperlinks?

**Comment by VadimDez** [comment] 2017-01-26 09:41
Not yet. Work in progress...

**Comment by gaurav2887** [comment] 2017-01-26 17:51
@VadimDez - Thanks. Please let me know once it's ready.

**Comment by VadimDez** [comment] 2017-01-27 19:32
Closing as duplicate of #18

**Closed by VadimDez** 2017-01-27 19:32 UTC
