### ISSUE TITLE
2.0.0+ doesn't work with ssr

### ISSUE THREAD

**Issue by glemiere** [VadimDez/ng2-pdf-viewer#173] opened 2017-10-01 16:12 UTC
Hi!

Everything is working fine using webpack and ssr with the version 1.2.7.
However since version 2.0.0 I get the following error when I start my dist/server.js file.

```
window['pdfjs-dist/build/pdf'] = pdfjs;
^

ReferenceError: window is not defined
```

**Comment by derrickbabb** [comment] 2017-10-03 21:38
Angular Universal also breaks with the same error during server-side rendering, where the window object is not available:
`
window['pdfjs-dist/build/pdf'] = pdfjs;
^

ReferenceError: window is not defined
    at Object.<anonymous> (../server.js:172048:1)
    at __webpack_require__ (../server.js:26:30)
    at Object.defineProperty.value (../server.js:172035:30)
    at __webpack_require__ (../server.js:26:30)
    at Object.defineProperty.value (../server.js:159976:73)
    at __webpack_require__ (../server.js:26:30)
    at Object.<anonymous> (../server.js:157478:93)
    at __webpack_require__ (../server.js:26:30)
    at Object.ROUTES (../server.js:151162:70)
    at __webpack_require__ (../server.js:26:30)
`
**Notes:**
- "ng2-pdf-viewer": "^2.0.2",
- Version 1.2.7 was working up until afternoon of 10/3/17.
- pdf-viewer is used inside of a modal window.

**Comment by glemiere** [comment] 2017-10-03 23:05
Thank you for these additionals informations @derrickbabb, I also forget to tell that it is coming from ssr.
I found a workaround adding the following to my webpack.server.config.js
```
    //Temporary fix for ng2-pdf-viewer undefined server-side variabled.
    new webpack.DefinePlugin({
      window: [],
      document: {}
    })
```

However then I have a new problem with Zone : 
```
/dist/server.js:105226
Zone.__load_patch('ZoneAwarePromise', function (global, Zone, api) {
^
```

I guess this library doesn't support SSR anymore :/

**Comment by glemiere** [comment] 2017-10-09 05:11
Any news about SSR support ?

**Comment by glemiere** [comment] 2017-10-21 00:42
up

**Comment by CanKattwinkel** [comment] 2017-10-25 12:04
I'm currently searching for an PDF viewer that supports Angular Universal. Are there any news on this issue? Would a reproduction repository help?

I don't really need PDF viewer on server side - maybe a simple solution would be to provide a noop-Module like the noopanimationsmodule..

**Comment by VadimDez** [comment] 2017-10-28 18:30
Would definitely save me some time if somebody provides a repo where i can reproduce this issue.

**Comment by LiverpoolOwen** [comment] 2017-11-20 22:05
@VadimDez any updates on this guys?

**Comment by VadimDez** [comment] 2017-11-21 13:36
I'll try to finish this by the end of this week.

**Comment by VadimDez** [comment] 2017-11-24 15:27
Fixed in `3.0.2`

**Closed by VadimDez** 2017-11-24 15:27 UTC
Labels: bug

**Comment by glemiere** [comment] 2017-11-27 17:11
Awesome! I'll test soon! ;-)
Thank you for your work!
Could you provide us a few explanation on the way you fixed this ? Could be interesting ;)

**Comment by CanKattwinkel** [comment] 2017-11-27 17:45
@glemiere https://github.com/VadimDez/ng2-pdf-viewer/pull/216/commits/c965b9ab8291a49c4c54f28c7b12af19b7180a7a

You can either wrap the Window/document statements with if checks or use the `document ` provided via dependency injection (supports querySelector and so on on server side since Angular 5 I think)

**Comment by glemiere** [comment] 2017-11-27 21:50
That's nice! Thank you!

**Comment by hesampour** [comment] 2018-08-12 08:15
Hi. I have problem in universal with the error Element is not defined. I found that the problem is for this component. Any Idea to fix that?

**Comment by arsenlol** [comment] 2018-10-31 13:37
+1 for previous comment:
webpack:///./node_modules/pdfjs-dist/build/pdf.js?:1080
    if (typeof Element.prototype.remove !== 'undefined') {
ReferenceError: Element is not defined

**Comment by shahbazkhan054** [comment] 2019-01-31 16:19
any update on it?

**Comment by kkorte** [comment] 2019-02-05 12:06
@hesampour @arsenlol @shahbazkhan054 

> any update on this?
> `ReferenceError: Element is not defined`

We encountered the same problem, and fixed it in prerender.ts & server.ts by adding the following lines:

```
win.requestAnimationFrame = () => {};
global['Element'] = {
    prototype: {}
};
```

**Comment by Bizotics-Dev** [comment] 2020-07-22 10:49
@VadimDez can you check this error reproduced again  in v5.3.4.
