### ISSUE TITLE
Out of bounds index in pdf_viewer: "TypeError: Cannot read property 'div' of undefined" - when closing PDF too quickly - or zooming

### ISSUE THREAD

**Issue by subatomicglue** [VadimDez/ng2-pdf-viewer#367] opened 2018-08-20 21:57 UTC
Seems to be a race-condition type of bug, if I close the pdf viewer too quickly.  (or change [zoom])

I get this with `ng2-pdf-viewer` v5.1.1 (angular 5.2) in Chrome if I close (set `*ngIf=false` the parent's `div`) too quickly before the PDF is totally loaded...    I have a "close" button that kills the pdfviewer parent div.   To guard it, to only be able to close when the PDF is loaded, I am catching the `(after-load-complete)` and `(page-rendered)`, not allowing to set the pdfviewer parent div's `ngIf` to false unless those have completed, but still getting the crash/exception.

```
TypeError: Cannot read property 'div' of undefined
    at backtrackBeforeAllVisibleElements (VM474151 pdf_viewer.js:558)
    at getVisibleElements (VM474151 pdf_viewer.js:605)
    at PDFViewer._getVisiblePages (VM474151 pdf_viewer.js:5400)
    at PDFViewer.forceRendering (VM474151 pdf_viewer.js:5080)
    at PDFRenderingQueue.renderHighestPriority (VM474151 pdf_viewer.js:4191)
    at continueRendering (VM474151 pdf_viewer.js:4256)
    at ZoneDelegate.invoke (VM472116 zone.js:388)
```

offending line of code is here in `pdf_viewer.js:558`:
```
function backtrackBeforeAllVisibleElements(index, views, top) {
  if (index < 2) {
    return index;
  }
  var elt = views[index].div;   <----- HERE pdf_viewer.js:558
```
where `index == 3` for my 3-page pdf (**out of bounds!**).

The html template:
```
<div *ngIf='showing' (click)="close()">
<div (click)="$event.stopPropagation()">
<pdf-viewer
	[src]='content_url'
        [zoom]='pdfzoom'
	[original-size]="false"
	[render-text]="true"
	[autoresize]="true"
	[show-all]="true"
	[fit-to-page]="false"
	(after-load-complete)="onPdfLoad($event)"
	(error)="onPdfError($event)"
	(on-progress)="onPdfProgress($event)"
	(page-rendered)="onPdfRendered($event)"
></pdf-viewer>
</div>
</div>
```

the `component.ts`
```
close() {
   if (this.can_close) this.showing = false;
}
onPdfLoad(e) {
  this.can_close = true;
}
zoomIn() {
  if (this.can_close) {
    this.pdfzoom = Math.min( this.pdfzoom_max, this.pdfzoom+0.1 );
  }
}
zoomOut() {
  if (this.can_close) {
    this.pdfzoom = Math.max( this.pdfzoom_min, this.pdfzoom-0.1 );
  }
}
```

**Comment by subatomicglue** [comment] 2018-08-20 21:57
see also https://github.com/VadimDez/ng2-pdf-viewer/issues/354

**Comment by subatomicglue** [comment] 2018-08-20 22:27
I get this also when changing the [zoom] parameter...

**Comment by jaronwright** [comment] 2018-08-21 14:35
Hey so I had the same issue. I noticed that if you added a bounds check for index it fixes the issue. The problem is actually with another package that ng2-pdf-viewer depends on. 

```
function backtrackBeforeAllVisibleElements(index, views, top) {
  if (index < 2 || views.length <= index) {
    return index;
  }
  console.log('index: ', index, 'view length: ', views.length);
  
  var elt = views[index].div;
  var pageTop = elt.offsetTop + elt.clientTop;
  if (pageTop >= top) {
    elt = views[index - 1].div;
    pageTop = elt.offsetTop + elt.clientTop;
  }
  for (var i = index - 2; i >= 0; --i) {
    elt = views[i].div;
    if (elt.offsetTop + elt.clientTop + elt.clientHeight <= pageTop) {
      break;
    }
    index = i;
  }
  return index;
}
```
 So I am pretty sure that  ng2-pdf-viewer has to run this check before calling 
```backtrackBeforeAllVisibleElements```

**Comment by subatomicglue** [comment] 2018-08-21 14:38
Confirmed this fixes the issue.   Looks like we'll need one of two fixes:

1. pull request into pdf_viewer
2. change ng2-pdf-viewer to not feed data to pdf_viewer that exceeds these bounds (I dont know if this is possible).

**Comment by subatomicglue** [comment] 2018-08-21 16:00
Looks like it's #2, `ng2-pdf-viewer` needs to fix the way it uses `pds.js`, see here:

https://github.com/mozilla/pdf.js/pull/9895#issuecomment-405515206

**Comment by subatomicglue** [comment] 2018-08-21 16:14
In the meantime, I have to wrap timers around my close and zoom buttons, to prevent the user from changing them too fast:

- Wait 3.5 seconds before presenting the close button
- Wait 1 second between changing zoom

```
  zoomIn() {
    if (this.can_close) {
      this.pdfzoom = Math.min( this.pdfzoom_max, this.pdfzoom+0.1 );
      this.can_close = false;
      setTimeout( () => {
        this.can_close = true;
      }, 1000 );
    }
  }
  zoomOut() {
    if (this.can_close) {
      this.pdfzoom = Math.max( this.pdfzoom_min, this.pdfzoom-0.1 );
      this.can_close = false;
      setTimeout( () => {
        this.can_close = true;
      }, 1000 );
    }
  }
  onPdfLoad() {
    // takes some time for the PDF to load - if close too early browser can crash
    setTimeout( () => {
      this.can_close = true;
    }, 3500 );
    console.log( "loaded" );
  }
  close() {
    // protect against closing the pdf viewer while it's loading (which can cause a crash)
    if (this.can_close)
      this.showing = false;
  };
```

**Comment by subatomicglue** [comment] 2018-08-21 18:09
The question I have, is:  

How is anyone using ng2-pdf-viewer without running into all kinds of these crashes in `pdf_viewer.js` (in pdf.js) ?   

Follow on question:

Am I using ng2-pdf-viewer wrong somehow?   Feels like my simple `[zoom]` increment/decrementer can't possibly be abusing the system....  It's so simple...   like it's exposing an internal bug of `ng2-pdf-viewer`.

**Comment by subatomicglue** [comment] 2018-08-21 20:31
I see that the demo page doesn't have the bug: https://vadimdez.github.io/ng2-pdf-viewer/
I pasted my `package.json` above, as you can see I am using `angular 5.2` and `angular-cli 1.7.1`

**Comment by subatomicglue** [comment] 2018-08-21 20:49
Very Simple Demo which reproduces, using vadimdez's pdf:
```
<div (click)="pdfshow = !pdfshow">close</div>
<div (click)="pdfzoom=1 < (pdfzoom+0.1) ? 1 : (pdfzoom+0.1)">zoomin</div>
<div (click)="pdfzoom=(pdfzoom-0.1) < 0.1 ? 0.1 : (pdfzoom-0.1)">zoomout</div>
<div *ngIf='pdfshow'>
	viewer:
	<pdf-viewer *ngIf="pdfshow" (click)="$event.stopPropagation()" style='background-color:black;display: block;'
		[src]="'https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf'"
		[original-size]="false"
		[render-text]="true"
		[autoresize]="true"
		[show-all]="true"
		[zoom]="pdfzoom"
		[fit-to-page]="false"
	></pdf-viewer>
</div>
```
If I hit close too quick, or hit zoomin/zoomout too quick, I'll get the same crash as above.

**Comment by subatomicglue** [comment] 2018-08-21 21:12
Very Simple Demo which reproduces, using vadimdez's pdf:

See here for a minimal, self contained, Angular 5.2.0 app: https://github.com/subatomicglue/ng2pdfViewerTest

The code added is thus:

Added to `app.component.html`:
```
<div (click)="pdfshow = !pdfshow">close</div>
<div (click)="pdfzoom=1 < (pdfzoom+0.1) ? 1 : (pdfzoom+0.1)">zoomin</div>
<div (click)="pdfzoom=(pdfzoom-0.1) < 0.1 ? 0.1 : (pdfzoom-0.1)">zoomout</div>
<div *ngIf='pdfshow'>
	viewer:
	<pdf-viewer *ngIf="pdfshow" (click)="$event.stopPropagation()" style='background-color:black;display: block;'
		[src]="'https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf'"
		[original-size]="false"
		[render-text]="true"
		[autoresize]="true"
		[show-all]="true"
		[zoom]="pdfzoom"
		[fit-to-page]="false"
	></pdf-viewer>
</div>
```

Added to `app.component.ts`:
```
  pdfshow:boolean = true;
  pdfzoom:boolean = true;
```
If I hit close too quick, or hit zoomin/zoomout too quick, I'll get the same crash as above.

**Comment by subatomicglue** [comment] 2018-08-21 21:27
Very Simple Demo which reproduces, using vadimdez's pdf:

See here for a minimal, self contained, Angular 5.2.0 app: https://github.com/subatomicglue/ng2pdfViewerTest

The code added is thus:

Added to `app.component.html`:
```
<div (click)="pdfshow = !pdfshow">close</div>
<div (click)="pdfzoom=1 < (pdfzoom+0.1) ? 1 : (pdfzoom+0.1)">zoomin</div>
<div (click)="pdfzoom=(pdfzoom-0.1) < 0.1 ? 0.1 : (pdfzoom-0.1)">zoomout</div>
<div *ngIf='pdfshow'>
	viewer:
	<pdf-viewer *ngIf="pdfshow" (click)="$event.stopPropagation()" style='background-color:black;display: block;'
		[src]="'https://vadimdez.github.io/ng2-pdf-viewer/assets/pdf-test.pdf'"
		[original-size]="false"
		[render-text]="true"
		[autoresize]="true"
		[show-all]="true"
		[zoom]="pdfzoom"
		[fit-to-page]="false"
	></pdf-viewer>
</div>
```

Added to `app.component.ts`:
```
  pdfshow:boolean = true;
  pdfzoom:number = 0.8;
```
If I hit close too quick, or hit zoomin/zoomout too quick, I'll get the same crash as above.

**Comment by Pringels** [comment] 2018-08-23 09:26
I also encountered this bug @subatomicglue . I attempted a similar solution to yours. (guarding zoom/close with a loading flag)

In my case I solved the problem by only setting the loaded flag once _all_ pages have rendered. (See below example)

It would be great if the lib could maybe emit an additional `(after-render-complete)` event or something. 

I know this still remains a less-than-optimal workaround but perhaps it helps you :)

**Container component class:**
```js
export class PdfViewerComponent {

  // ... 

  loaded = false;
  showPdf = true; 
  pageCount: number;
  pagesRendered: number;

  pdfLoaded = event => {
    this.pageCount = event.pdfInfo.numPages;
  };

  pageRendered = () => {
    this.pagesRendered += 1;
    if (this.pagesRendered === this.pageCount) {
      this.renderComplete();
    }
  };

  renderComplete = () => {
    this.loaded = true;
  }

  close = () => {
     if (this.loaded) {
        this.showPdf = false;
     }
  }

  // ...

}
```

**Container component template:**
```html
<div *ngIf="showPdf">
  <pdf-viewer [src]="pdfSrcConfig"
              [autoresize]="true"
              [original-size]="false"
              (page-rendered)="pageRendered($event)"
              (after-load-complete)="pdfLoaded($event)"
  ></pdf-viewer>
</div>

```

**Comment by subatomicglue** [comment] 2018-08-29 16:11
Super smart.  Love it.  (Hate that I have to do this).  But you found a solid solution.  Thanks for sharing!

**Comment by alaahwanas** [comment] 2018-09-13 03:34
error when closing large pdf too early.. any help?

**Comment by Pringels** [comment] 2018-10-01 08:13
Can you paste some examples of your code?

**Comment by jorgepsmatos** [comment] 2018-12-05 01:51
I have the same error when changing the route before the finishing the render of all pages. 

Any updates?

**Comment by jorgepsmatos** [comment] 2018-12-05 11:18
Actually, I can't reproduce the problem in the [example](https://vadimdez.github.io/ng2-pdf-viewer/).

But using the change in pdf_viewer.js solves my problem.

I'll keep investigating

**Comment by noamyg** [comment] 2019-01-24 09:01
@jiangyh1024 delete your package-lock.json, your node_modules, then run `yarn install` and try again

**Comment by jiangyh1024** [comment] 2019-01-24 09:14
@noamyg  
![image](https://user-images.githubusercontent.com/34930870/51667673-6b5cb180-1ffb-11e9-9ec1-802b7190a37f.png)

is it related to the version of pdfjs-dist ?

**Comment by koggalage** [comment] 2019-04-22 04:39
I had the same error and I fixed it with following changes.

* ng2-pdf-viewer has a dependency called pdfjs-dist. You can find it in node_modules.
* Open this file -> node_modules/pdfjs-dist/web/pdf_viewer.js
* In pdf_viewer.js file, search for this line of code -> `var elt = views[index].div;` It is inside 'backtrackBeforeAllVisibleElements' function.
* Change that code line to `var elt = views[index-1].div;` and save.

**Comment by moast** [comment] 2019-04-22 20:27
> Hey so I had the same issue. I noticed that if you added a bounds check for index it fixes the issue. The problem is actually with another package that ng2-pdf-viewer depends on.
> 
> Line 555: pdf_viewer.js
> 
> ```
> function backtrackBeforeAllVisibleElements(index, views, top) {
>   if (index < 2 || views.length <= index) {
>     return index;
>   }
>   console.log('index: ', index, 'view length: ', views.length);
>   
>   var elt = views[index].div;
> ```
> So I am pretty sure that ng2-pdf-viewer has to run this check before calling
> 
> `backtrackBeforeAllVisibleElements`

That fixed the issue for me. So strange though coz it still don't understand the index check!

**Comment by KensingtonTech** [comment] 2019-04-23 00:20
This is a big problem for a lot of people, and it has thus far received no apparent attention from the author.   We have it from the authors of pdf_viewer.js that ng2-pdf-viewer is using the library incorrectly.

@VadimDez, with all due respect, are you looking at your issue tracker?  Would you please chime in here and give us some help?  People are having to use some pretty cruddy workarounds to get around this.

**Comment by robert-king** [comment] 2019-04-25 22:38
my fix for now, global error handler ignores this error when i close material dialog:

```

@Injectable()
export class MyErrorHandler implements ErrorHandler {
  //https://medium.com/@amcdnl/global-error-handling-with-angular2-6b992bdfb59c
  constructor(
    private injector: Injector
  ) {
  }

  handleError(error: any) {
    console.error(error);
    if (error.message.startsWith(`Uncaught (in promise): TypeError: Cannot read property 'div' of undefined
TypeError: Cannot read property 'div' of undefined
    at backtrackBeforeAllVisibleElements`)) {
      // https://github.com/VadimDez/ng2-pdf-viewer/issues/367
      console.log('ignoring error');
      return;
    }
    setTimeout(() => {
      const errorService: ErrorService = this.injector.get(ErrorService);
      errorService.genericError();
    },1);
  }
}

```

**Comment by MaximYesman** [comment] 2019-06-10 11:12
Looks like issue was fixed 
#354

**Comment by VadimDez** [comment] 2019-07-28 18:49
Does this error still occur with version `>5.3.1` ?

**Closed** 2019-10-10 18:54 UTC

**Comment by BemHur** [comment] 2020-03-30 18:31
Hey guys, im using this with a ionic v4 app and if use the zoom prop and try do drag to another page the app crashes, no erros are shown in the console. Any suggestions are welcome.
Version:
 "ng2-pdf-viewer": "^6.1.2",

**Comment by moast** [comment] 2020-03-30 18:42
Unfortunately, I did not find any solutions yet. However, I replaced it with webview instead. So when users want to read a PDF take them to a webview instead, it work perfectly.

**Comment by BemHur** [comment] 2020-03-30 18:51
> 
> 
> Unfortunately, I did not find any solutions yet. However, I replaced it with webview instead. So when users want to read a PDF take them to a webview instead, it work perfectly.

Yeah, i have already tried 3 pdf libs out, all crashes when zooming. The webview is displayed inside the app or it open another page?

**Comment by moast** [comment] 2020-03-30 19:05
You can open it in the app if you specific the target to be equal to _self
and _system if you want to open in the device browser
checkout this
https://github.com/apache/cordova-plugin-inappbrowser

**Comment by dhruvit27** [comment] 2020-09-26 06:42
Hello i am getting my pdfComponent undefined although i have written in a correct formate.
![image](https://user-images.githubusercontent.com/51944132/94332248-1bfd2e80-fff1-11ea-8f88-21be8ae404c7.png)
here i am putting the declaration image
![image](https://user-images.githubusercontent.com/51944132/94332264-4cdd6380-fff1-11ea-92fa-a93a831c8fa9.png)

so @VadimDez can yo please help me out to solve this error
thank you
