### ISSUE TITLE
call back if error encounterd 

### ISSUE THREAD

**Issue by praveenpds** [VadimDez/ng2-pdf-viewer#117] opened 2017-08-03 08:58 UTC
Can you provide similar to (after-load-complete)="callBackFn($event)"
for if url is not reachable or server timeout ??

(on-error)="callBackFn($event)"

**Comment by VadimDez** [comment] 2017-08-03 08:59
Duplicate of #112

**Comment by praveenpds** [comment] 2017-08-03 09:00
Oh..sorry

**Closed by VadimDez** 2017-08-03 08:59 UTC
