### ISSUE TITLE
Getting PDF text

### ISSUE THREAD

**Issue by shessafridi** [VadimDez/ng2-pdf-viewer#734] opened 2021-03-05 16:13 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [x] Documentation issue or request
```

I can't find a way to get selected text, is there any way to get selected text ?

**Comment by VadimDez** [comment] 2021-03-11 10:16
Duplicate of #729

**Closed by VadimDez** 2021-03-11 10:16 UTC
