### ISSUE TITLE
Warnings with Angular 9/10/11 and using of old pdfjs-dist library

### ISSUE THREAD

**Issue by maerni** [VadimDez/ng2-pdf-viewer#757] opened 2021-04-13 13:34 UTC
Hi

We have some warnings in Angular 9/10/11, see below. When this library would be updated to remove this warnings? And when the library would work with the newset pdfjs-dist?

Thanks very much.

Here the warnings:
Warning: Entry point 'ng2-pdf-viewer' contains deep imports into 
'/node_modules/pdfjs-dist/es5/build/pdf', '/node_modules/pdfjs-dist/es5/web/pdf_viewer'. 
This is probably not a problem, but may cause the compilation of entry points to be out of order.

Warning: C:\tgdaemi1\workspace-git\ecs-ui\node_modules\ng2-pdf-viewer\__ivy_ngcc__\fesm2015\ng2-pdf-viewer.js depends on 'pdfjs-dist/es5/build/pdf'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\tgdaemi1\workspace-git\ecs-ui\node_modules\ng2-pdf-viewer\__ivy_ngcc__\fesm2015\ng2-pdf-viewer.js depends on 'pdfjs-dist/es5/web/pdf_viewer'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by 06MasonG** [comment] 2021-04-22 11:06
Changing pdfjs-dist dependency to [https://www.npmjs.com/package/@bundled-es-modules/pdfjs-dist]?

**Comment by michael-letcher** [comment] 2021-05-07 06:09
Duplicate of #754

**Comment by arturovt** [comment] 2021-05-20 18:25
@maerni 

> When this library would be updated to remove this warnings

Warnings are coming from the NGCC compiler and not from the library itself, this happens because of how Mozilla ships the `pdfjs-dist` package. To remove the deep import warning follow this comment: https://github.com/VadimDez/ng2-pdf-viewer/issues/754#issuecomment-845359425

To remove "optimization bailouts" warning follow this example: https://github.com/VadimDez/ng2-pdf-viewer/blob/master/angular.json#L34-L37

**Closed** 2021-05-20 21:06 UTC
