### ISSUE TITLE
cannot read property 'div' of undefined

### ISSUE THREAD

**Issue by DEBOJYOTI11** [VadimDez/ng2-pdf-viewer#351] opened 2018-07-23 05:26 UTC
`
- [ ] Bug report -> please search issues before submitting
`

When I pop the page which renders the pdf file using Ionic's Navcontroller, I am getting the following error 

```
core.js:1449 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'div' of undefined
TypeError: Cannot read property 'div' of undefined
    at backtrackBeforeAllVisibleElements (pdf_viewer.js:558)
    at getVisibleElements (pdf_viewer.js:605)
    at PDFViewer._getVisiblePages (pdf_viewer.js:5400)
    at PDFViewer.forceRendering (pdf_viewer.js:5080)
    at PDFRenderingQueue.renderHighestPriority (pdf_viewer.js:4191)
    at continueRendering (pdf_viewer.js:4256)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at backtrackBeforeAllVisibleElements (pdf_viewer.js:558)
    at getVisibleElements (pdf_viewer.js:605)
    at PDFViewer._getVisiblePages (pdf_viewer.js:5400)
    at PDFViewer.forceRendering (pdf_viewer.js:5080)
    at PDFRenderingQueue.renderHighestPriority (pdf_viewer.js:4191)
    at continueRendering (pdf_viewer.js:4256)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
```

I am using Ionic 3.20.0 and ng2-pdf-viewer ^5.1.1

**Comment by josepfdc** [comment] 2018-07-23 08:18
I have the same problem.
I make a menu list that when I click on item show a pdf file. The problem or issue happens after click on any item for second time.

I check different configurations of pdf-viewer and no work

<pdf-viewer [src]="info_menuactivo.link_pdf"  [render-text]="true" *ngIf="onChequear_formato_pdf_activo()"
          style="display: block;"></pdf-viewer>

I use angular cli 1.8
I tested with Chrome and error is the following:

```
core.js:1633 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'div' of undefined
TypeError: Cannot read property 'div' of undefined
    at backtrackBeforeAllVisibleElements (pdf_viewer.js:558)
    at getVisibleElements (pdf_viewer.js:605)
    at PDFViewer._getVisiblePages (pdf_viewer.js:5400)
    at PDFViewer.forceRendering (pdf_viewer.js:5080)
    at PDFRenderingQueue.renderHighestPriority (pdf_viewer.js:4191)
    at continueRendering (pdf_viewer.js:4256)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3760)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at backtrackBeforeAllVisibleElements (pdf_viewer.js:558)
    at getVisibleElements (pdf_viewer.js:605)
    at PDFViewer._getVisiblePages (pdf_viewer.js:5400)
    at PDFViewer.forceRendering (pdf_viewer.js:5080)
    at PDFRenderingQueue.renderHighestPriority (pdf_viewer.js:4191)
    at continueRendering (pdf_viewer.js:4256)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:3760)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at resolvePromise (zone.js:814)
    at zone.js:877
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3751)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
    at HTMLDivElement.globalZoneAwareCallback (zone.js:1566)
```


The error in Safari is the following:

```
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'views[index].div') backtrackBeforeAllVisibleElements@http://localhost:4200/vendor.js:162522:25 getVisibleElements@http://localhost:4200/vendor.js:162569:63 forceRendering@http://localhost:4200/vendor.js:167044:72 renderHighestPriority@http://localhost:4200/vendor.js:166155:40 continueRendering@http://localhost:4200/vendor.js:166220:40 onInvoke@http://localhost:4200/vendor.js:56217:39 run@http://localhost:4200/polyfills.js:2460:49 http://localhost:4200/polyfills.js:3194:37 onInvokeTask@http://localhost:4200/vendor.js:56208:43 runTask@http://localhost:4200/polyfills.js:2510:57 drainMicroTaskQueue@http://localhost:4200/polyfills.js:2917:42 invokeTask@http://localhost:4200/polyfills.js:2822:40 invokeTask@http://localhost:4200/polyfills.js:3862:20 globalZoneAwareCallback@http://localhost:4200/polyfills.js:3888:27
resolvePromise — zone.js:814
(funció anònima) — zone.js:877
onInvokeTask — core.js:3751
runTask — zone.js:188
drainMicroTaskQueue — zone.js:595
invokeTask — zone.js:500
invokeTask — zone.js:1540
globalZoneAwareCallback — zone.js:1566
```

I hope this help to resolve this issue

Thank you in advance for your help

Frank Deza

**Comment by VadimDez** [comment] 2018-07-23 20:50
Duplicate of #224

**Closed by VadimDez** 2018-07-23 20:50 UTC
