### ISSUE TITLE
How to print a pdf?

### ISSUE THREAD

**Issue by tonychangcheng** [VadimDez/ng2-pdf-viewer#107] opened 2017-07-12 00:20 UTC
I am looking for a solution to print a pdf file. 

I found the pdf.js has a web/viewer which supports printing and other features. As ng2-pdf-viewer underneath is using pdf.js. Dose it provide a wrap of the web/viewer? Or does it have a plan to do that?

**Comment by tonychangcheng** [comment] 2017-07-12 00:21
And does it support displaying a pdf from a base64 buffer?

**Comment by bhupinderkumarbl** [comment] 2017-08-09 10:11
I did with simply call this function on click 

printpdf() {
        this.winRef.open(this.pdfSrc).print();
    }

**Comment by VadimDez** [comment] 2017-08-10 21:03
Duplicate of #69

**Closed by VadimDez** 2017-08-10 21:03 UTC

**Comment by jacobbutton** [comment] 2018-03-05 14:40
@bhupinderkumarbl - how are you declaring and initializing `this.winRef` ?

**Comment by bibhukdas** [comment] 2018-08-20 17:43
Convert your blob to URL, and print it. Works for me.
const fl = URL.createObjectURL(this.fileBlob);
window.open(fl).print();

**Comment by rohanrp** [comment] 2019-02-15 06:41
I got it to print using 

const blobUrl  = window.URL.createObjectURL((this.srcBinary);
const iframe = document.createElement('iframe');
iframe.style.display = 'none';
iframe.src = blobUrl;
document.body.appendChild(iframe);
iframe.contentWindow.print();

**Comment by fredfgb** [comment] 2019-05-09 21:23
> printpdf() {
> this.winRef.open(this.pdfSrc).print();
> }

Here explains how to use "winRef", just a bootstrap for nativeWindow

**Comment by alehro** [comment] 2019-10-23 08:38
Simpler approach with example is in https://github.com/intbot/ng2-pdfjs-viewer/issues/7
