### ISSUE TITLE
hello， how can I zoom PDF according to gestures？

### ISSUE THREAD

**Issue by yytian1017** [VadimDez/ng2-pdf-viewer#341] opened 2018-06-29 07:26 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```

**Comment by VadimDez** [comment] 2018-06-29 21:13
Duplicate of #22

**Closed by VadimDez** 2018-06-29 21:13 UTC
