### ISSUE TITLE
Failed to execute 'postMessage' on 'Worker': TypeError: fs.lstat is not a function could not be cloned

### ISSUE THREAD

**Issue by jrupik** [VadimDez/ng2-pdf-viewer#326] opened 2018-05-22 08:58 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When pdf-viewer src is set to local file in electron + angular 6 application the following error is thrown:

Unhandled Promise rejection: Failed to execute 'postMessage' on 'Worker': TypeError: fs.lstat is not a function could not be cloned. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'postMessage' on 'Worker': TypeError: fs.lstat is not a function could not be cloned.
    at MessageHandler.postMessage (file:///C:/Projects/_classic-collector/app/vendor.js:76981:19)
    at sendStreamRequest (file:///C:/Projects/_classic-collector/app/vendor.js:76798:14)
    at file:///C:/Projects/_classic-collector/app/vendor.js:76863:7
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (file:///C:/Projects/_classic-collector/app/polyfills.js:11566:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (file:///C:/Projects/_classic-collector/app/polyfills.js:11316:43)
    at file:///C:/Projects/_classic-collector/app/polyfills.js:12050:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (file:///C:/Projects/_classic-collector/app/polyfills.js:11599:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (file:///C:/Projects/_classic-collector/app/polyfills.js:11366:47)
    at drainMicroTaskQueue (file:///C:/Projects/_classic-collector/app/polyfills.js:11773:35)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (file:///C:/Projects/_classic-collector/app/polyfills.js:11678:21) Error: Failed to execute 'postMessage' on 'Worker': TypeError: fs.lstat is not a function could not be cloned.
    at MessageHandler.postMessage (file:///C:/Projects/_classic-collector/app/vendor.js:76981:19)
    at sendStreamRequest (file:///C:/Projects/_classic-collector/app/vendor.js:76798:14)
    at file:///C:/Projects/_classic-collector/app/vendor.js:76863:7
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (file:///C:/Projects/_classic-collector/app/polyfills.js:11566:26)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (file:///C:/Projects/_classic-collector/app/polyfills.js:11316:43)
    at file:///C:/Projects/_classic-collector/app/polyfills.js:12050:34
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (file:///C:/Projects/_classic-collector/app/polyfills.js:11599:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (file:///C:/Projects/_classic-collector/app/polyfills.js:11366:47)
    at drainMicroTaskQueue (file:///C:/Projects/_classic-collector/app/polyfills.js:11773:35)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (file:///C:/Projects/_classic-collector/app/polyfills.js:11678:21)
api.onUnhandledError @ zone.js:665
handleUnhandledRejection @ zone.js:692
_loop_1 @ zone.js:682
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1577

html looks like:

  <pdf-viewer *ngIf="imageVisible && resourceList[imageIndex].type=='PDF'"
                      [src]="getImagePath(resourceList[imageIndex].filename)"
                      [page]="1"
                      [show-all]="true"
                      [render-text]="true"
                      style="display: block;"
                      class="fit-object-height-fill">
          </pdf-viewer>

getImagepath() returns: file:///C:/Projects/_data/file.pdf

With angular 5 all work correctly.

**Comment by VadimDez** [comment] 2018-05-22 09:03
Perhaps duplicate of #180

**Comment by jrupik** [comment] 2018-05-22 12:01
I have preapared component based on your idea from #180 and #58

```ts
import {Component, Input, OnDestroy, OnInit} from '@angular/core';
import {Observable} from "rxjs";
import {Subscription} from "rxjs";

@Component({
  selector: 'cc-local-pdf-viewer',
  template: `<pdf-viewer *ngIf="previewSrc" 
                         [src]="previewSrc" 
                         [show-all]="true"
                         [render-text]="true"
                         style="display: block;"
                         class="fit-object-height-fill"></pdf-viewer>`
})
export class LocalPdfViewerComponent implements OnInit, OnDestroy {

  @Input()
  private filePath: string = null;
  public previewSrc: string = null;
  private subscription: Subscription = null;

  ngOnInit() {
      this.subscription = this.getFile(this.filePath).subscribe(value => {
        this.previewSrc = value;
      });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
  }

  getFile(path: string): Observable<any> {
    // console.log('getFile path: %s', path);
    return Observable.create((observer: any) => {
      new Promise<string>((resolve, reject) => {

        const request = new XMLHttpRequest();
        request.open('GET', path, true);
        request.responseType = 'blob';

        request.onload = () => {
          const reader = new FileReader();

          reader.onload = (e: any) => resolve(e.target.result);
          reader.onerror = err => reject(err);
          reader.readAsDataURL(request.response);
        };

        request.send();
      }).then((data) => {
        observer.next(data);
      }, (reason) => {
        observer.error(reason);
      });
    });
  }
}
```

but it doesn't work (error below), could you help?

core.js:1598 ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
    at MessageHandler.postMessage (pdf.js:1357)
    at sendStreamRequest (pdf.js:1174)
    at pdf.js:1239
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4062)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)
    at MessageHandler.postMessage (pdf.js:1357)
    at sendStreamRequest (pdf.js:1174)
    at pdf.js:1239
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4062)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)
    at resolvePromise (zone.js:814)
    at zone.js:877
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4053)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
    at Worker.globalZoneAwareCallback (zone.js:1577)

**Comment by jrupik** [comment] 2018-05-23 05:48
Hi,
I don't understand what is said in #180 about fetch api. I have prepared component loading pdf file using this api and it is working perfectly. Also I don't understand why your component stop working after angular upgrade to version 6, with version 5 works correctly.

LocalPdfViewerComponent:

```ts
import {ChangeDetectorRef, Component, Input, OnDestroy, OnInit} from '@angular/core';
import {Observable} from "rxjs/Observable";
import {Subscription} from "rxjs/Subscription";
import {takeUntil} from "rxjs/operators";
import {Subject} from "rxjs/index";

@Component({
  selector: 'cc-local-pdf-viewer',
  template: `<pdf-viewer *ngIf="previewSrc" 
                         [src]="previewSrc" 
                         [show-all]="true"
                         [render-text]="true"
                         style="display: block;"
                         class="fit-object-height-fill"></pdf-viewer>`
})
export class LocalPdfViewerComponent implements OnInit, OnDestroy {

  @Input()
  private filePath: string = null;
  public previewSrc: string = null;
  private ngUnsubscribe: Subject<Subscription> = new Subject();

  constructor(private changeDetectorRef: ChangeDetectorRef){}

  ngOnInit() {
     this.readFile(this.filePath).pipe(takeUntil(this.ngUnsubscribe)).subscribe(data => {
      let reader = new FileReader();
      reader.onloadend = (e: any) => {
        this.previewSrc = e.target.result;
        this.changeDetectorRef.detectChanges();
      };
      reader.readAsArrayBuffer(data);
    });
  }

  ngOnDestroy() {
    this.ngUnsubscribe.next();
    this.ngUnsubscribe.complete();
  }


  readFile(path: string): Observable<any> {
    console.log('readFile path: %s', path);
    return Observable.create(observer => {
      fetch(path)
        .then(response => response.blob()) // or text() or blob() etc.
        .then(data => {
          observer.next(data);
          observer.complete();
        })
        .catch(err => observer.error(err));
    })
  }

}
```

component usage in html:
```html
<cc-local-pdf-viewer [filePath]="file:///C:/_data/info.pdf"></cc-local-pdf-viewer>
```
Could you explain it?
Regards,
Joachim Rupik

**Comment by MateEke** [comment] 2018-06-25 14:43
I can't use angular 6 + pdfjs + electron. In browser everything works perfectly, but in electron app  I get the same error as you:

```
ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
Error: Failed to execute 'postMessage' on 'Worker': TypeError: https.request is not a function could not be cloned.
```

Any solution?

**Comment by jrupik** [comment] 2018-06-25 15:11
@MateEke : try to use my last example, that is works for me - it displays a local file (file:///).

**Comment by MateEke** [comment] 2018-06-26 06:55
@jrupik   Thank you! 
Now I can load the pdf with HttpClient, convert it to ArrayBuffer, and this way PDFJS displays it.
Not a nice solution, but it works.

**Comment by mungpara** [comment] 2019-03-16 06:16
```
this.http.get('path', {responseType: 'arraybuffer'}).subscribe(value => {
this.src= value;
});
```

try this

**Closed** 2019-10-10 19:03 UTC
