### ISSUE TITLE
.ng2-pdf-viewer-container not in parent container

### ISSUE THREAD

**Issue by Gabriel2409** [VadimDez/ng2-pdf-viewer#811] opened 2021-07-30 09:20 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [X] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
File : pdf-viewer.component.scss

In the latest version, the .ng2-pdf-viewer-container is set with position:absolute and width:100%
This leads to multiple styling problems, especially in pages where the pdf viewer is supposed to be contained in a container. 

In previous versions, the position was set to relative and there was no problems.

**Comment by nischi** [comment] 2021-08-04 05:01
Workaround could be to set the container <pdf-viewer> to position:relative. Took me also i while to figure out.

**Comment by almothafar** [comment] 2021-08-20 12:04
I think it is a duplicate of #805 (workaround provided)
Here is the change to blame: https://github.com/VadimDez/ng2-pdf-viewer/commit/8d4f8ad25107a98e920ab18e32b828c2e5597e54#diff-c0a5f3426a537629a18cbeb63abc55b7ce727f267c2e85acf84c88ddd96e4cb1R3

**Comment by axell9641** [comment] 2021-09-09 16:57
> Workaround could be to set the container to position:relative. Took me also i while to figure out.

I can't thank you enough. I was going insane. The example in the demo worked fine and mine just didn't.

**Comment by VadimDez** [comment] 2021-11-15 20:15
Checkout [7.0.2](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/7.0.2) release, should be better now, I've also included breaking change note.

**Closed by VadimDez** 2021-11-15 20:15 UTC
