### ISSUE TITLE
Oh my god!

### ISSUE THREAD

**Issue by jiangyh1024** [VadimDez/ng2-pdf-viewer#435] opened 2019-01-24 02:38 UTC
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
@ColinT 

I came across a problem. 

```
<button (click)="click()">click</button>
<div style="max-height: 200px; max-width: 500px; position: relative; overflow: auto">
  <pdf-viewer *ngIf="pdfSrc" [autoresize]="true" [(page)]="pdfNo" [zoom]="zoom" class="pdf-viewer" [original-size]="false"
    [show-all]="true" [src]="pdfSrc" [render-text]="false">
  </pdf-viewer>
</div>
  click(index: number): void {
    this.pdfNo = 13;
  }

```
above code works in version 5.2.x,  not work in version 5.1.x

it threw an error if using version 5.1.x, and [(page)] two-way binding did not work if I scroll to another page, it did not reflect to the variable 'pdfNo'
![_s0cs__lg0ulyf zs25e1](https://user-images.githubusercontent.com/34930870/51650716-38e39200-1fc4-11e9-9e9c-b71d280898b2.png)

**Comment by jiangyh1024** [comment] 2019-01-24 02:45
I added [stick-to-page]="true",  also threw an error 
![image](https://user-images.githubusercontent.com/34930870/51650926-100fcc80-1fc5-11e9-9437-efd417ff660d.png)

**Comment by jiangyh1024** [comment] 2019-01-24 02:46
Currently I use [show-all]="false", and added button for use to go to the next or prev page, it works. But why  [show-all]="true" had such a weird behavior

**Comment by ColinT** [comment] 2019-01-24 07:11
Duplicate of https://github.com/VadimDez/ng2-pdf-viewer/issues/367

I am able to reproduce this error, and have provided a repository for it [here](https://github.com/ColinT/npv-tester/tree/issue-435/src).
(I tried to create a Stackblitz but it gets hung on importing `zlib-bindings` due to a problem in the older `pdfjs-dist` dependency version.)

---

Using `[stick-to-page]="true"` should give you at least some of the functionality you want. It looks like the underlying `pdfjs-dist` library is not scrolling properly without this option.

The error you are receiving is due to an array out of bounds error. See image:
`// pdf-viewer.js:558`
![image](https://user-images.githubusercontent.com/3926408/51659833-c77ef180-1f79-11e9-9ed0-309e52abe9c2.png)
**Note: `index = 58, views = Array(58)`**

There is an array `views` of length `X` where `X` is the number of pages in the pdf. For some reason it is trying to access `views[X]`, which is out of bounds. I'm not sure why this is occurring.

Even though this error is being thrown from `pdfjs-dist` code it should be noted that this is indeed a bug in `ng2-pdf-viewer`. See https://github.com/mozilla/pdf.js/pull/9895#issuecomment-405515206.

There are some preliminary solutions offered in https://github.com/VadimDez/ng2-pdf-viewer/issues/367. Have you tried these?

**Comment by jiangyh1024** [comment] 2019-01-24 07:15
@ColinT  Thanks a lot!!!!!! I will try it

**Comment by VadimDez** [comment] 2019-04-28 12:01
Duplicate of  #367

**Closed by VadimDez** 2019-04-28 12:01 UTC
