### ISSUE TITLE
Warning in Angular 10

### ISSUE THREAD

**Issue by xiaoxiangmoe** [VadimDez/ng2-pdf-viewer#643] opened 2020-08-07 16:20 UTC
##### Bug Report or Feature Request (mark with an `x`)

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request

```
./node_modules/ng2-pdf-viewer/__ivy_ngcc__/fesm2015/ng2-pdf-viewer.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.ts" URL is not supported
```

Use this lib in angular 10 with sourcemap will case warning.

Update ng-packagr to 10 will remove this warning for angular 10 users.

**Comment by Blunderchips** [comment] 2020-09-05 19:28
@xiaoxiangmoe is this still a problem?

**Comment by si-fab** [comment] 2020-09-17 15:51
Yes this is still a problem.

**Comment by xiaoxiangmoe** [comment] 2020-11-17 02:29
1

**Comment by xiaoxiangmoe** [comment] 2021-01-16 06:50
1

**Comment by xiaoxiangmoe** [comment] 2021-01-16 06:51
好好学习

**Comment by xiaoxiangmoe** [comment] 2021-01-16 06:53
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by xiaoxiangmoe** [comment] 2021-01-17 05:34
@stale No

**Comment by xiaoxiangmoe** [comment] 2021-03-18 07:24
1312

**Comment by xiaoxiangmoe** [comment] 2021-05-19 03:35
1

**Comment by xiaoxiangmoe** [comment] 2021-07-18 14:04
321321

**Comment by xiaoxiangmoe** [comment] 2021-09-16 16:56
11

**Comment by Akxe** [comment] 2021-11-11 14:11
This is a duplicate of https://github.com/VadimDez/ng2-pdf-viewer/issues/624. Let's close this one and subscribe there ;)

**Comment by xiaoxiangmoe** [comment] 2022-01-11 16:41
ok

**Closed** 2022-01-11 16:42 UTC
